// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.uber.org/zap"
	"wechat-bot/biz/friend"
	"wechat-bot/biz/group"
	"wechat-bot/dao/gpt"
	"wechat-bot/dao/wechat"
	wechat2 "wechat-bot/service/wechat"
)

// Injectors from wire.go:

func initServer(log *zap.SugaredLogger) (*Server, error) {
	bot := wechat.NewBot()
	gptGPT := gpt.NewGPT()
	friendFriend := friend.NewFriend(log, gptGPT)
	groupGroup := group.NewGroup(log, gptGPT)
	wechatWechat := wechat2.NewWechat(bot, friendFriend, groupGroup, log)
	server := NewServer(wechatWechat)
	return server, nil
}
